= LF_LoRa Library for Arduino =

This library is intended to create LoRa devices that communicate with the LoRa2MQTT, Home Assistant AddOn.

It is limited to ESP32 processors (all versions) because it uses specific resources of this platform.

The examples can be used for initial experience with the device / LoRa2MQTT pair.

The example "LF_LoRa_USB_Adapter_01" is to flash the USB adapter to be connected to the Home Assistant server and allow connection to devices.

Each example contains a corresponding LoRa MQTT configuration file. This example .ino / .py file pair serves as a basis for developing new devices.

== License ==

Copyright (c) 2011-2025 Arduino LLC. All right reserved.
Copyright (c) 2025-2025 Leonardo Figueiro.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

<!-- Markdown link -->
[project-stage-shield]: https://img.shields.io/badge/project%20stage-development%20beta-red.svg
[maintenance-shield]: https://img.shields.io/maintenance/yes/2025.svg
[github_LF_LoRa]: https://github.com/leofig-rj/Arduino-LF_LoRa
[docs_link]: https://github.com/leofig-rj/leofig-hass-addons/blob/master/lora2mqtt/DOCS.md
[github_leofig-rj]: https://github.com/leofig-rj
