= LF_LoRa Library for Arduino =

This handle LF_Lora Devices for LoRa2MQTT Home Assistant AddOn.

For more information about this library please ask
leoagfig@gmail.com

== License ==

Copyright (c) 2011-2025 Arduino LLC. All right reserved.
Copyright (c) 2025-2025 Leonardo Figueiro.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
